name: generate-debs

on: push

jobs:
  build_humble:
    runs-on: ubuntu-22.04
    steps:
      - uses: esteve/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          REPOS_FILE: https://raw.githubusercontent.com/esteve/autoware/custom-repos/autoware.repos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true

  build_rolling:
    runs-on: ubuntu-22.04
    steps:
      - uses: esteve/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: rolling
          REPOS_FILE: https://raw.githubusercontent.com/esteve/autoware/custom-repos/autoware.repos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
